# ===============================================
# Profile: Testing (test)
# ===============================================
# Purpose: For running automated unit and integration tests.
# Database: H2 In-Memory (provides a clean, isolated environment for each test run).

spring:
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:orderdb_test # Use a different DB name to avoid conflicts with dev
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  # JPA/Hibernate Settings for Testing
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # 'create-drop' ensures tests run against a predictable schema.
      ddl-auto: create-drop
    # It's good practice to keep SQL logs off during tests to reduce console noise.
    show-sql: false
